env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=dottravis"
   - secure: "JXE+FZ30zzvZdROmYqzeuC+/5fTZZCU/5yOndxuuyunFmTEAHd9xvBPXiNSmQwR459o2+5cV0xwZjNEBRR2JvoOZ656WOQfWypM7OPGXt0q6xZfqjwnHRZ8MByy+ZnsGootVuvONpjBSaMAPcypDK1VLNzetssWwKDb9CQIqP8E="
   - secure: "WTGS+w2qkusP7K8HIyTI/2UJ29mhs5HsMGnJP4M55ImBDvNr4fzrwv4aecuAbbPAm+dHr/yyuQWKW6BOQhgf+y6waxwUwKNJ3DlGrdnTADqa7yjP1Fs95hGcCoSGaxqQlmiWtbHCfvYdXvXoe1sBdtC2Bjb0ZNHrv2xHsFxB60o="
   - secure: "IfIHLfMYc2k/B4wiekPMf3I8dw7HwiY/co4W6uViI/CQDudi/vDF5vQfjh5sH+jdIrU0TF+Fo+Ezu32o2CuYyf7Y1puyH4EGT6wwY7157YfkmhsxpsR3Ki81k9Juv95mkkBBi9P74+VikyuNjufia0TQ07nATqQrWny8J5CiInQ="

language: python
python:
  - "2.7"
rvm:
  - "2.1.2"
before_script:
  - bundle install
  - sudo apt-get install libcfitsio3-dev python-matplotlib python-pyfits python-scipy
  - pip install -r requirements.txt --use-mirrors
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python baseline.py
after_script:
  # Only upload to Travis and make a comment if there is a pull request associated with this build
  - ruby status.rb
