env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=dottravis"
   - secure: "JXE+FZ30zzvZdROmYqzeuC+/5fTZZCU/5yOndxuuyunFmTEAHd9xvBPXiNSmQwR459o2+5cV0xwZjNEBRR2JvoOZ656WOQfWypM7OPGXt0q6xZfqjwnHRZ8MByy+ZnsGootVuvONpjBSaMAPcypDK1VLNzetssWwKDb9CQIqP8E="
   - secure: "WTGS+w2qkusP7K8HIyTI/2UJ29mhs5HsMGnJP4M55ImBDvNr4fzrwv4aecuAbbPAm+dHr/yyuQWKW6BOQhgf+y6waxwUwKNJ3DlGrdnTADqa7yjP1Fs95hGcCoSGaxqQlmiWtbHCfvYdXvXoe1sBdtC2Bjb0ZNHrv2xHsFxB60o="
   - secure: "JEvbK1N3w8VGrmkkEUKanHK03E6yRtVB74pcgdi/KCeynDySwDoZZdu2xpY+xodpHUN9LEDUPCk5IoMIFfy4JtY3+Bgx1wMScQSHv5phAfH3g8Den0wr8Uvi3FHnHvT+pWxGqo2jlJJZHQExRpSekBsHaX/dKDXyGqwnGeCc6uU="

language: python
python:
  - "2.7"
rvm:
  - "2.1.2"
before_script:
  - bundle install
  - sudo apt-get install libcfitsio3-dev python-matplotlib python-pyfits python-scipy
  - pip install -r requirements.txt --use-mirrors
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python baseline.py
after_script:
  - "travis-artifacts upload --path assets/result.png:result-$TRAVIS_PULL_REQUEST.png"
  - curl -u "science-champ:$GITHUB_AUTH" -H "Content-Type: application/json" -d '{"body":"test"}' https://api.github.com/repos/arfon/dottravis/issues/$TRAVIS_PULL_REQUEST/comments
