# Probably the worst way to do this, but let's define the competition model parameters here
model_parameters:
  - "m"
  - "b"
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=dottravis"
   - secure: "Qpc4cZLxLVgOrRoe00/tYoJQXIGFnqAlNSjZgQc1K/BNT9vRd5oi/deYKSeU5/I0Y38QdRj79sO1OnWckPJPV/TcFJ+yhsJpx+oTs3E62SnMcXxEloxig6iFPMnIIyc4PRY4mlLz72uvJ12I4N8oAmnCNnyD+a6tbkwIKGo36ko="
   - secure: "QuOS4Ot5jwGMe5SPW7IEnrPk1ke9uL6A40qC4nx90myjEYGgRJoPlGPZQVdsXACk2UyPHCKZ5W3h+FcIEuboxf29Zy/bVQLfjFDoFG3LxxPkF+xb6TK69VEWKp2kb//P7Hf+svaut8/a899W1PVR8+t/mq9OU4JkUYHtwD+67Bo="
   - secure: "PpcGL3Lh7W6dnZ48zio/zaE7lsCAgfm1lL5vNZtZFiobKO1qfah3rT+X8KdLoMYHSpgmCrAMKr5sk2WOxd9sbCIi0IX5R/5lT8VEn/mHWWHhwZarVGwGh8P9wozt5rn7brk+75BW7pf7RfkJNwIttTAbGk1A2bL48XyFR/ATVrA="

language: python
python:
  - "2.7"
rvm:
  - "2.1.2"
before_script:
  - bundle install
  - sudo apt-get install python-matplotlib python-scipy
  - pip install -r requirements.txt --use-mirrors
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python baseline.py
after_script:
  # Only upload to Travis and make a comment if there is a pull request associated with this build
  - bundle exec ruby status.rb 
